version: '3'
services:
    db_sql:
      image: mysql:5.7
      volumes:
       - ./db_data:/var/lib/mysql
      restart: always
      ports:
       - 33066:3306
      environment:
        MYSQL_ROOT_PASSWORD: 1234
